export const AUTH_MOCK_USER = {
  firstName: "John",
  lastName: "Doe",
  email: "john@doe.com",
  password: "asdfasdf",
  phone: "413-413-4133",
  address: "123 Main St",
  city: "Springfield",
  state: "MA",
  zip: "01103",
};

export const AUTH_MOCK_USER_UPDATE = {
  firstName: "Jane",
  lastName: "Smith",
  email: "john@doe.com",
  password: "asdfasdf",
  phone: "133-133-1333",
  address: "321 Main Dr.",
  city: "Enfield",
  state: "CT",
  zip: "12345",
};

export const STATIC_MOCK_USER_1 = {
  firstName: "User",
  lastName: "One",
  email: "one@mockuser.com",
  password: "mockuser1",
  phone: "111-111-1111",
  address: "1 User Dr.",
  city: "Userville",
  state: "NY",
  zip: "11111",
};

export const STATIC_MOCK_USER_2 = {
  firstName: "User",
  lastName: "Two",
  email: "two@mockuser.com",
  password: "mockuser2",
  phone: "222-222-2222",
  address: "2 User Dr.",
  city: "Userland",
  state: "NY",
  zip: "11111",
};

export const MOCK_EVENT = {
  date: "2025-10-15",
  time: "17:00",
  locationDescription: "Around back",
  address: "123 Circle Dr.",
  city: "West Springfield",
  state: "MA",
  zip: "01089",
  guests: 25,
  hours: 4,
  eventType: "Birthday",
  needBar: true,
  needTent: false,
  needAlcohol: true,
  needDrinkware: true,
  beer: true,
  wine: true,
  specialtyDrinks: false,
  liquorPreferences: "Premium liquors only.",
  additionalInfo: "Great web site!",
};

export const MOCK_EVENT_UPDATE = {
  date: "2026-10-15",
  time: "18:00",
  locationDescription: "Around front. Can't miss it.",
  address: "321 Square St.",
  city: "East Winterfield",
  state: "CT",
  zip: "01111",
  guests: 20,
  hours: 3,
  eventType: "Anniversary",
  needBar: false,
  needTent: true,
  needAlcohol: false,
  needDrinkware: false,
  beer: false,
  wine: false,
  specialtyDrinks: true,
  liquorPreferences: "Inexpensive liquors only.",
  additionalInfo: "Your web site is terrible!",
};
